"""initial

Revision ID: 55c7633d1cd7
Revises: 
Create Date: 2026-01-15 10:37:25.081001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c7633d1cd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('enrollment_start_date', sa.Date(), nullable=True),
    sa.Column('enrollment_end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fee_concepts',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('concept_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_types_id'), ['id'], unique=False)

    op.create_table('fee_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('value_bs', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['fee_concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('section_code')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_national_id'), ['national_id'], unique=True)

    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('student_user_id', 'section_id', 'subject_id', name='uq_student_section_subject')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('proof_url', sa.String(length=255), nullable=True),
    sa.Column('invoice_url', sa.String(length=255), nullable=True),
    sa.Column('bank_reference', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['fee_concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('prerequisites',
    sa.Column('main_subject_id', sa.Integer(), nullable=False),
    sa.Column('required_subject_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['main_subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['required_subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('main_subject_id', 'required_subject_id')
    )
    op.create_table('section_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('professor_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_subjects')
    op.drop_table('prerequisites')
    op.drop_table('payments')
    op.drop_table('enrollments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_national_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('sections')
    op.drop_table('fee_schedules')
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_types_id'))

    op.drop_table('user_types')
    op.drop_table('programs')
    op.drop_table('fee_concepts')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
