"""Add student_grades and program_subjects

Revision ID: 668bea1405b9
Revises: bbd98bee658b
Create Date: 2026-04-06 12:03:58.405310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668bea1405b9'
down_revision: Union[str, Sequence[str], None] = 'bbd98bee658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_grades',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('numeric_grade', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('grade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_grades')
    op.drop_table('program_subjects')
    # ### end Alembic commands ###
